root: true
env:
  node: true
  browser: true
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:astro/recommended'
  - 'plugin:astro/jsx-a11y-recommended'
  - 'prettier'
plugins:
  - '@typescript-eslint'
  - 'jsx-a11y'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
ignorePatterns:
  - '@types/**/*'
# rules:

overrides:
  - files: '*.astro'
    parser: 'astro-eslint-parser'
    parserOptions:
      extraFileExtensions: ['.astro']
    globals:
      astroHTML: true
    # rules:

  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
      - '*.mjs'
    extends:
      - 'plugin:react/recommended'
    settings:
      react:
        version: '18'
    rules:
      react/react-in-jsx-scope: 'off'
