tabWidth: 2
printWidth: 80
semi: false
arrowParens: 'always'
singleQuote: true
trailingComma: 'all'
importOrder:
  - '^@(.*)$'
  - '<THIRD_PARTY_MODULES>'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
plugins:
  - 'prettier-plugin-astro'
overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
