extends:
  - stylelint-config-html
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-prettier
  - stylelint-config-recess-order
overrides:
  - files:
      - './**/*.astro'
    customSyntax: 'postcss-html'

rules:
  string-quotes: single
  selector-class-pattern: null
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  no-invalid-position-at-import-rule: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - mixin
        - include
        - extend
        - function
        - return
        - use
  no-empty-source: null
  'scss/at-extend-no-missing-placeholder': null
  # scss/at-function-pattern: null
  # scss/at-mixin-pattern: null
  # scss/at-extend-no-missing-placeholder: null
  # no-descending-specificity: null
